const UserActionTypes = {
    CHANGE_MODE : "CHANGE_MODE",
    PLAY_MUSIC : "PLAY_MUSIC",
    PAUSE_MUSIC : "PAUSE_MUSIC",
    PLAY_NEXT_MUSIC : "PLAY_NEXT_MUSIC",
    PLAY_PREVIOUS_MUSIC : "PLAY_PREVIOUS_MUSIC",
    OPEN_MENU : "OPEN_MENU",
    CLOSE_MENU : "CLOSE_MENU",
    SET_CURRENT_MUSIC : "SET_CURRENT_MUSIC",
    LIKE_MUSIC : "LIKE_MUSIC",
}

export default UserActionTypes;