const UserActionTypes = {
    CHANGE_MODE : "CHANGE_MODE",
    PLAY_CURRENT_MUSIC : "PLAY_CURRENT_MUSIC",
    PAUSE_CURRENT_MUSIC : "PAUSE_CURRENT_MUSIC",
    PLAY_NEXT_MUSIC : "PLAY_NEXT_MUSIC",
    PLAY_PREVIOUS_MUSIC : "PLAY_PREVIOUS_MUSIC",
    OPEN_MENU : "OPEN_MENU",
    CLOSE_MENU : "CLOSE_MENU",
}

export default UserActionTypes;